// <auto-generated />
namespace ConsultorioMedico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Populacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Populacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201710102219378_Populacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
